export const data = JSON.parse("{\"key\":\"v-6386bf70\",\"path\":\"/md/dev-log/%E6%94%AF%E4%BB%98%E5%95%86%E5%9F%8E%E7%B3%BB%E7%BB%9F.html\",\"title\":\"上线项目1-支付商城系统（维护中）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"上线项目1-支付商城系统（维护中）\",\"index\":false,\"icon\":\"construction\",\"category\":[\"开发笔记\",\"学习记录\"],\"description\":\"🚧 当前状态：项目文档维护中 本项目文档正在整理与完善中，敬请期待更新上线。 📎 快速预览 点击下方按钮访问演示站： 立即访问项目主页 🚀 [//]: # (## 任务) [//]: # () [//]: # (- [x] 环境配置) [//]: # (- [x] 搭建项目结构) [//]: # (- [x] 跑通广播模式 RPC 过程调用) [...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/md/dev-log/%E6%94%AF%E4%BB%98%E5%95%86%E5%9F%8E%E7%B3%BB%E7%BB%9F.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"我的简历\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"上线项目1-支付商城系统（维护中）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🚧 当前状态：项目文档维护中 本项目文档正在整理与完善中，敬请期待更新上线。 📎 快速预览 点击下方按钮访问演示站： 立即访问项目主页 🚀 [//]: # (## 任务) [//]: # () [//]: # (- [x] 环境配置) [//]: # (- [x] 搭建项目结构) [//]: # (- [x] 跑通广播模式 RPC 过程调用) [...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"许哲远\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"上线项目1-支付商城系统（维护中）\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"许哲远\\\",\\\"url\\\":\\\"http://localhost:8080/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🚧 当前状态：项目文档维护中\",\"slug\":\"🚧-当前状态-项目文档维护中\",\"link\":\"#🚧-当前状态-项目文档维护中\",\"children\":[]},{\"level\":2,\"title\":\"📎 快速预览\",\"slug\":\"📎-快速预览\",\"link\":\"#📎-快速预览\",\"children\":[]}],\"readingTime\":{\"minutes\":5.1,\"words\":1529},\"filePathRelative\":\"md/dev-log/支付商城系统.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
