export const data = JSON.parse("{\"key\":\"v-0e2c9650\",\"path\":\"/md/dev-log/%E8%AF%84%E5%AE%A1%E7%BB%84%E4%BB%B6.html\",\"title\":\"上线项目2-评审组件（维护）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"上线项目2-评审组件（维护）\",\"index\":false,\"icon\":\"construction\",\"category\":[\"开发笔记\",\"学习记录\"],\"description\":\"🚧 当前状态：项目文档维护中 本项目文档正在整理与完善中，可先体验上线项目。 🎯 本系统基于 Spring AI + DeepSeek 模型 实现，支持自动化代码审查、语义增强分析、RAG 私有知识接入等功能，广泛适用于企业代码 CI 流程。 📎 快速预览 点击下方按钮访问演示站： 立即访问项目主页-评审组件前端 🚀 [//]: # (## 任...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/md/dev-log/%E8%AF%84%E5%AE%A1%E7%BB%84%E4%BB%B6.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"我的简历\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"上线项目2-评审组件（维护）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🚧 当前状态：项目文档维护中 本项目文档正在整理与完善中，可先体验上线项目。 🎯 本系统基于 Spring AI + DeepSeek 模型 实现，支持自动化代码审查、语义增强分析、RAG 私有知识接入等功能，广泛适用于企业代码 CI 流程。 📎 快速预览 点击下方按钮访问演示站： 立即访问项目主页-评审组件前端 🚀 [//]: # (## 任...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"许哲远\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"上线项目2-评审组件（维护）\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"许哲远\\\",\\\"url\\\":\\\"http://localhost:8080/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🚧 当前状态：项目文档维护中\",\"slug\":\"🚧-当前状态-项目文档维护中\",\"link\":\"#🚧-当前状态-项目文档维护中\",\"children\":[]},{\"level\":2,\"title\":\"📎 快速预览\",\"slug\":\"📎-快速预览\",\"link\":\"#📎-快速预览\",\"children\":[]}],\"readingTime\":{\"minutes\":5.27,\"words\":1581},\"filePathRelative\":\"md/dev-log/评审组件.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
